const fs=require('fs'),path=require('path'),http=require('http');
const {chromium}=require('C:/Users/안동현/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..');
(async()=>{
const server=http.createServer((req,res)=>{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(pathname==='/js/data/config.js'||pathname==='/js/data/firebase-config.js'){res.setHeader('Content-Type','application/javascript');return res.end('window.firebaseDb=null;window.isFirebaseReady=false;');}if(pathname==='/api/chat'){res.writeHead(503);return res.end('Audit: AI network disabled');}const f=path.resolve(root,'.'+(pathname==='/'?'/index.html':pathname));if(!f.startsWith(root+path.sep)){res.writeHead(403);return res.end();}fs.readFile(f,(e,b)=>{if(e){res.writeHead(404);return res.end();}res.setHeader('Content-Type',f.endsWith('.js')?'application/javascript':f.endsWith('.css')?'text/css':'text/html');res.end(b);});});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});
const context=await browser.newContext({viewport:{width:1440,height:900}});
await context.route('**/*',route=>{const u=route.request().url();if(u.includes('firebase')||u.includes('upstage')||u.includes('firestore'))return route.abort();return route.continue();});
const page=await context.newPage();const errors=[],consoleErrors=[],results=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text());});page.on('dialog',d=>d.dismiss());
await page.goto(url,{waitUntil:'networkidle'});

async function probe(name,fn){try{results.push({name,value:await page.evaluate(fn)});}catch(e){results.push({name,error:e.message});}}
await probe('all navigation pairs',()=>{const states=['roadmap','unit1','unit2','unit3','eval','classroom'];isTeacherAuthenticated=true;const out=[];for(const from of states){for(const to of states){switchUnit('roadmap');switchUnit(from,from==='unit3'?'lab':null);if(from==='unit3')switchFlowchartStep(5);switchUnit(to,to==='unit3'?'lab':null);if(to==='unit3')switchFlowchartStep(5);const visible=[...document.querySelectorAll('main')].filter(e=>e.getBoundingClientRect().height>0).map(e=>e.id);out.push({from,to,visible});}}return out;});
await page.goto(url,{waitUntil:'networkidle'});
await probe('mission validation correct and wrong',()=>missions.map(m=>{const slots=m.slots.filter(s=>!s.fixed);const correct=Object.fromEntries(slots.map((s,i)=>[s.id,m.palette[i].id]));const wrong={...correct,[slots[0].id]:m.palette[1].id,[slots[1].id]:m.palette[0].id};return {id:m.id,correct,correctPass:m.validate(correct),wrongPass:m.validate(wrong),emptyPass:m.validate({})};}));
await probe('quiz answer and retry',()=>Object.entries(UNIT_QUIZ_DATA).map(([k,v])=>{for(const q of v.questions){const i=q.options.findIndex(o=>!o.correct);handleQuizAnswer(k,q.id,i,false);}const wrong=Object.values(userQuizAnswers[k]).filter(a=>a.isCorrect).length;for(const q of v.questions){const i=q.options.findIndex(o=>o.correct);handleQuizAnswer(k,q.id,i,true);}return {unit:k,wrongCount:wrong,correctCount:Object.values(userQuizAnswers[k]).filter(a=>a.isCorrect).length};}));
await page.evaluate(()=>{switchUnit('unit3','lab');switchFlowchartStep(1);});
const inv=await page.locator('[draggable="true"]').evaluateAll(es=>es.filter(e=>e.getBoundingClientRect().height).map(e=>({id:e.id,text:e.innerText})));results.push({name:'draggable inventory',value:inv});
await probe('puzzle replacement conservation',()=>{selectFlowchartMission(1);const ev={preventDefault(){},dataTransfer:{getData(){return 'b-m1-1';}}};draggedBlockId='b-m1-1';handleDrop(ev,'s2');draggedBlockId='b-m1-2';handleDrop(ev,'s2');return {placed:placedBlocks,inventory:document.getElementById('block-inventory')?.innerText};});
await probe('wrong puzzle sim shows expected instead',async()=>{selectFlowchartMission(2);placedBlocks={s2:'b-m2-1',s3:'b-m2-2',s4_yes:'b-m2-no',s4_no:'b-m2-yes'};renderCanvasSlots(missions[1]);document.getElementById('test-user-height').value='160';const prev=highlightNode;highlightNode=async()=>{};await runFlowchartSimulation();highlightNode=prev;return {valid:missions[1].validate(placedBlocks),output:document.getElementById('io-output-display').textContent,trace:document.getElementById('tracer-log').innerText};});
await page.goto(url,{waitUntil:'networkidle'});await page.evaluate(()=>{switchUnit('unit3','lab');switchFlowchartStep(5);});await page.waitForTimeout(500);
const before=await page.evaluate(()=>freeBlocks.length);await page.locator('#fc-level3-view .palette-block-io').dblclick().catch(e=>results.push({name:'palette actual double click error',error:e.message.slice(0,200)}));results.push({name:'palette actual double click',value:{before,after:await page.evaluate(()=>freeBlocks.length)}});
await probe('block coordinate move setup',()=>{const b=freeBlocks.find(b=>b.shape==='process');return b?{id:b.id,x:b.x,y:b.y}:null;});
const pb=page.locator('#fc-level3-view .free-block').first();const rect=await pb.boundingBox();if(rect){await page.mouse.move(rect.x+30,rect.y+15);await page.mouse.down();await page.mouse.move(rect.x+80,rect.y+35,{steps:5});await page.mouse.up();results.push({name:'actual block drag',value:await page.evaluate(()=>freeBlocks.map(b=>({id:b.id,x:b.x,y:b.y})))});}
await probe('parser matrix',()=>{const arithmetic=['x=2+3*4','x=(2+3)*4','x=-2*3','x=7%3','x=3.14','x=.5','x=1.2.3','x=..5','x=2/0','x=2%0','x=z+1','x=(2+3'];return arithmetic.map(text=>{try{const a=parseFlowchartAssign(text);return {text,value:evalFlowchartAST(a.ast,{})};}catch(e){return {text,error:e.message};}});});
await probe('portfolio actual image',async()=>{const c=await generatePortfolioCanvas('검증01','테스트');window.auditPortfolio=c.toDataURL();return {width:c.width,height:c.height};});const imageData=await page.evaluate(()=>auditPortfolio);fs.writeFileSync(path.join(__dirname,'portfolio.png'),Buffer.from(imageData.split(',')[1],'base64'));
for(const width of [1920,1440,1366,1024,768]){await page.goto(url,{waitUntil:'networkidle'});await page.setViewportSize({width,height:width===1366?768:900});await page.evaluate(()=>{switchUnit('unit3','lab');switchFlowchartStep(5);});await page.waitForTimeout(600);await page.screenshot({path:path.join(__dirname,'fresh-studio-'+width+'.png')});results.push({name:'fresh studio geometry '+width,value:await page.evaluate(()=>{const e=document.getElementById('free-flowchart-canvas'),r=e.getBoundingClientRect();const bar=document.getElementById('sim-drag-floating-bar').getBoundingClientRect();return {canvas:{x:r.x,y:r.y,width:r.width,height:r.height},bar:{x:bar.x,y:bar.y,width:bar.width,height:bar.height},overflow:document.documentElement.scrollWidth>innerWidth};})});}
await page.goto(url,{waitUntil:'networkidle'});await page.setViewportSize({width:1440,height:900});await page.evaluate(()=>{switchUnit('eval');studentEvalApp.startExam();studentEvalApp.switchPart('part3');['io','decision','process','terminal'].forEach(s=>studentEvalApp.addPart3Block(s));});await page.waitForTimeout(600);await page.screenshot({path:path.join(__dirname,'eval-shapes.png')});
await probe('evaluation block shapes versus port geometry',()=>studentEvalApp.answers.part3.blocks.map(b=>{const e=document.getElementById('eval-blk-'+b.id);const r=e.getBoundingClientRect();const p=e.querySelector('.port-bottom')?.getBoundingClientRect();return {shape:b.shape,actual:{width:r.width,height:r.height},expectedBottom:studentEvalApp.getPortCoordinates(b,'out'),actualBottom:p?{x:p.x-r.x+7,y:p.y-r.y+7}:null,background:getComputedStyle(e).backgroundColor};}));
await probe('evaluation score and answers count',()=>{const a=new StudentEvalApp();EVAL_QUESTIONS.part1.forEach(q=>a.answers.part1[q.id]=q.correctAnswer);EVAL_QUESTIONS.part2.forEach(q=>a.answers.part2[q.id]=' '+q.answers[0].split('').join(' ')+' ');return {part1Count:EVAL_QUESTIONS.part1.length,part2Count:EVAL_QUESTIONS.part2.length,scores:a.calculateScores().scores};});
await probe('evaluation rejoin clears existing answers',async()=>{await evalService.joinWaitingRoom('audit-rejoin',1,'테스트');const listKey='EVAL_STUDENTS_audit-rejoin';const list=JSON.parse(sessionStorage.getItem(listKey));list[0].answers.part1={p1_q1:2};list[0].status='in_progress';sessionStorage.setItem(listKey,JSON.stringify(list));await evalService.joinWaitingRoom('audit-rejoin',1,'테스트');return JSON.parse(sessionStorage.getItem(listKey))[0];});
fs.writeFileSync(path.join(__dirname,'coverage-results.json'),JSON.stringify({results,errors,consoleErrors},null,2));console.log(JSON.stringify({results,errors,consoleErrors},null,2));await browser.close();server.close();})().catch(e=>{console.error(e);process.exitCode=1;});