const fs=require('fs'),path=require('path'),http=require('http');
const {chromium}=require('C:/Users/안동현/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..');
(async()=>{
const server=http.createServer((req,res)=>{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(pathname==='/js/data/config.js'||pathname==='/js/data/firebase-config.js'){res.setHeader('Content-Type','application/javascript');return res.end('window.firebaseDb=null;window.isFirebaseReady=false;');}if(pathname==='/api/chat'){res.writeHead(503);return res.end('Audit: AI network disabled');}const f=path.resolve(root,'.'+(pathname==='/'?'/index.html':pathname));if(!f.startsWith(root+path.sep)){res.writeHead(403);return res.end();}fs.readFile(f,(e,b)=>{if(e){res.writeHead(404);return res.end();}res.setHeader('Content-Type',f.endsWith('.js')?'application/javascript':f.endsWith('.css')?'text/css':'text/html');res.end(b);});});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});
const context=await browser.newContext({viewport:{width:1440,height:900}});
await context.route('**/*',route=>{const u=route.request().url();if(u.includes('firebase')||u.includes('upstage')||u.includes('firestore'))return route.abort();return route.continue();});
const page=await context.newPage();const errors=[],consoleErrors=[],results=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text());});page.on('dialog',d=>d.dismiss());
await page.goto(url,{waitUntil:'networkidle'});

async function probe(name,fn){try{results.push({name,value:await page.evaluate(fn)});}catch(e){results.push({name,error:e.message});}}
await probe('static handlers missing',()=>[...document.querySelectorAll('*')].flatMap(e=>[...e.attributes].filter(a=>a.name.startsWith('on')).map(a=>({element:e.id||e.tagName,event:a.name,code:a.value}))).map(x=>({...x,fn:(x.code.match(/^([A-Za-z_$][\w$]*)\s*\(/)||[])[1]})).filter(x=>x.fn&&typeof window[x.fn]==='undefined'&&!['if'].includes(x.fn)));
await probe('quiz all units',()=>Object.entries(UNIT_QUIZ_DATA).map(([k,v])=>({unit:k,count:v.questions.length,invalid:v.questions.filter(q=>q.options.filter(o=>o.correct).length!==1)})));
await probe('abstraction full tutorial',()=>{switchUnit('unit1','lab');applyTutStep1('지각 위기','정시 등교','late');nextTutorialStep();applyTutStep2(TUT_SCENARIOS.late.conditions[0].text);nextTutorialStep();TUT_SCENARIOS.late.noiseTags.forEach(toggleTutTrashTag);nextTutorialStep();nextTutorialStep();return {completed:isTutorialCompleted,tab:currentAbstractionSubTab,step:tutStep};});
await probe('abstraction offline prescription',async()=>{document.getElementById('inp-current').value='늦잠';document.getElementById('inp-goal').value='정시 등교';registeredConditions=['7시 기상'];currentPoolTags=['시각','알람','준비 시간'];currentTrashTags=[];await generateFinalPrescription();return window.latestAbstractionPrescription;});
await probe('mission validation',()=>missions.map(m=>({id:m.id,slots:m.slots,blocks:m.palette.map(b=>({id:b.id,text:b.text,shape:b.shape})),emptyPass:m.validate({})})));
await probe('sandwich correct and error actions',()=>{switchUnit('unit2','lab');resetWorkspace();const early=executeActionStep('TAKE_BREAD');const actions=['OPEN_BAG','TAKE_BREAD','TAKE_BREAD','OPEN_JAM','SCOOP_JAM','SPREAD_JAM_BREAD1_FLAT','OPEN_PB','SCOOP_PB','SPREAD_PB_BREAD2_FLAT','UNWRAP_CHEESE','PUT_CHEESE_BREAD1','COVER_BREAD_FLIPPED'];const outcomes=actions.map(executeActionStep);return {early,outcomes,result:analyzeSandwichResult()};});
await probe('sandwich fallback order',()=>['잼 뚜껑을 열고 칼에 잼을 떠서 빵에 골고루 발라','빵을 꺼내고 봉지를 열어','빵 봉지 열기'].map(text=>({text,parsed:fallbackRuleParser(text)})));
await probe('sandwich reset during active queue',async()=>{resetWorkspace();window._oldParser=parseWithSolarAI;parseWithSolarAI=async()=>({type:'ACTION',actions:['OPEN_BAG','OPEN_JAM','TAKE_BREAD']});document.getElementById('cmd-input').value='검증용 명령';await executeCommand();resetWorkspace();await new Promise(r=>setTimeout(r,1150));parseWithSolarAI=window._oldParser;return {state,queue:globalExecutionQueue};});
await probe('teacher assignment detail handler',()=>{isTeacherAuthenticated=true;switchUnit('classroom');switchClassroomSubTab('assignments');return {handler:typeof openStudentDetailModal,sampleRows:getClassroomData()['2학년 1반'].length};});
await probe('student name interpreted as executable HTML',async()=>{window.auditMarker=0;renderLiveGrid([{num:1,name:'<img src="/audit-missing-img" onerror="window.auditMarker=1">',status:'waiting'}]);await new Promise(r=>setTimeout(r,100));return {marker:window.auditMarker};});
await probe('submission rejected by server',async()=>{const old=evalService.getDb;evalService.getDb=()=>{const ref={collection:()=>ref,doc:()=>ref,set:async()=>{throw new Error('Audit simulated permission denied');}};return ref;};studentEvalApp.isSubmitted=false;await studentEvalApp.submitExam(true);evalService.getDb=old;return {submitted:studentEvalApp.isSubmitted,resultVisible:!document.getElementById('eval-screen-result').classList.contains('hidden')};});
await probe('AI outage still awards pass',async()=>{switchUnit('unit3','lab');switchFlowchartStep(5);freeBlocks=[{id:'s',shape:'terminal',text:'시작',x:200,y:30},{id:'p',shape:'process',text:'물 마시기',x:200,y:140},{id:'e',shape:'terminal',text:'종료',x:200,y:250}];freeConnections=[{from:'s',to:'p',fromPort:'bottom',toPort:'top'},{from:'p',to:'e',fromPort:'bottom',toPort:'top'}];nlCards=[{id:'n',type:'seq',text:'물 마시기'}];renderFreeCanvas();await diagnoseFreeAlgorithmWithSolarAI();return {passed:window.isFlowchartAiPassed,banner:document.getElementById('flowchart-ai-audit-modal').innerText};});
await probe('editing approved work preserves pass',()=>{closeAiAuditModal();handleBlockTextChange('p','');updateNlCardText('n','전혀 다른 행동');return {passed:window.isFlowchartAiPassed,consistency:analyzeAlgorithmConsistency()};});
await probe('single branch false follows yes',()=>{freeBlocks=[{id:'s',shape:'terminal',text:'시작',x:200,y:20},{id:'d',shape:'decision',text:'배가 고픈가?',x:200,y:120},{id:'p',shape:'process',text:'밥 먹기',x:200,y:240},{id:'e',shape:'terminal',text:'종료',x:200,y:350}];freeConnections=[{from:'s',to:'d',fromPort:'bottom',toPort:'top'},{from:'d',to:'p',fromPort:'yes',toPort:'top'},{from:'p',to:'e',fromPort:'bottom',toPort:'top'}];renderFreeCanvas();resetDebugger();stepDebugger();stepDebugger();handleSimDecisionChoice('d','아니오');return {current:debuggerExec.curId,previous:debuggerExec.prevId,log:document.getElementById('debug-terminal-console').innerText};});
await probe('portfolio image generation',async()=>{window.isFlowchartAiPassed=true;openThinkerSubmissionModal();const canvas=await generatePortfolioCanvas('테스트01','검증학생');return {width:canvas.width,height:canvas.height};});
await page.evaluate(()=>closeThinkerSubmissionModal());
for(const width of [1920,1440,1366,1024,768]){await page.setViewportSize({width,height:width===1366?768:900});await page.evaluate(()=>{switchUnit('unit3','lab');switchFlowchartStep(5);});await page.waitForTimeout(700);await page.screenshot({path:path.join(__dirname,'studio-'+width+'.png')});results.push({name:'studio geometry '+width,value:await page.evaluate(()=>{const ids=['sim-drag-floating-bar','free-flowchart-canvas','flowchart-studio-l3','debugger-panel'];return ids.map(id=>{const e=document.getElementById(id);if(!e)return {id,missing:true};const r=e.getBoundingClientRect();return {id,x:r.x,y:r.y,w:r.width,h:r.height,scrollW:e.scrollWidth,clientW:e.clientWidth};});})});}
await page.setViewportSize({width:1440,height:900});await page.evaluate(()=>{switchUnit('eval');studentEvalApp.sessionStatus='waiting';studentEvalApp.isSubmitted=false;studentEvalApp.startExam();studentEvalApp.switchPart('part3');});await page.waitForTimeout(600);await page.screenshot({path:path.join(__dirname,'eval-part3.png')});
fs.writeFileSync(path.join(__dirname,'deep-results.json'),JSON.stringify({results,errors,consoleErrors},null,2));console.log(JSON.stringify({results,errors,consoleErrors},null,2));await browser.close();server.close();})().catch(e=>{console.error(e);process.exitCode=1;});