const fs=require('fs'),path=require('path'),http=require('http');
const {chromium}=require('C:/Users/안동현/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..');
(async()=>{
const server=http.createServer((req,res)=>{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(pathname==='/js/data/config.js'||pathname==='/js/data/firebase-config.js'){res.setHeader('Content-Type','application/javascript');return res.end('window.firebaseDb=null;window.isFirebaseReady=false;');}if(pathname==='/api/chat'){res.writeHead(503);return res.end('Audit: AI network disabled');}const f=path.resolve(root,'.'+(pathname==='/'?'/index.html':pathname));if(!f.startsWith(root+path.sep)){res.writeHead(403);return res.end();}fs.readFile(f,(e,b)=>{if(e){res.writeHead(404);return res.end();}res.setHeader('Content-Type',f.endsWith('.js')?'application/javascript':f.endsWith('.css')?'text/css':'text/html');res.end(b);});});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});
const context=await browser.newContext({viewport:{width:1440,height:900}});
await context.route('**/*',route=>{const u=route.request().url();if(u.includes('firebase')||u.includes('upstage')||u.includes('firestore'))return route.abort();return route.continue();});
const page=await context.newPage();const errors=[],consoleErrors=[],results=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text());});page.on('dialog',d=>d.dismiss());
await page.goto(url,{waitUntil:'networkidle'});

async function probe(name,fn){try{results.push({name,value:await page.evaluate(fn)});}catch(e){results.push({name,error:e.message});}}
await probe('concept controls',()=>{switchUnit('unit1','concept');['init','curr','cond','goal'].forEach(showStateDetail);[1,3,5].forEach(n=>discardNoise('noise-card-'+n,true));const cleared=discardedNoiseCount;resetNoiseGame();toggleMapMode();toggleMapMode();['school','ramyeon'].forEach(switchDecompTab);switchUnit('unit2','concept');Object.keys(ALGO_5_CONDITIONS).forEach(toggleLampCondition);['vague','clear'].forEach(runRobotDefiniteness);['infinite','finite'].forEach(runFinitenessSim);switchUnit('unit3','concept');Object.keys(SYMBOL_ENTRY_MAP).forEach(showSymbolEntryDetail);['seq','sel','loop'].forEach(switchStructureTab);return {noiseCleared:cleared,noiseReset:discardedNoiseCount,symbols:SYMBOL_ENTRY_MAP};});
await probe('actual timer callback after suspended clock',()=>{const oldInterval=window.setInterval,oldNow=Date.now;let tick;window.setInterval=(fn,ms)=>{tick=fn;return 98765;};studentEvalApp.startExam({startTime:new Date().toISOString(),durationMinutes:30});window.setInterval=oldInterval;Date.now=()=>oldNow()+120000;tick();Date.now=oldNow;studentEvalApp.timerInterval=null;return {remaining:studentEvalApp.remainingSeconds,expected:1680};});
await probe('runtime completion toast removed by cleanup',()=>{switchUnit('roadmap');switchUnit('unit3','lab');switchFlowchartStep(4);showL2CompletionToast('audit completion');const before=document.querySelectorAll('.l2-sim-complete-toast').length;clearL2SimulationHighlights();return {before,after:document.querySelectorAll('.l2-sim-complete-toast').length};});
await page.goto(url,{waitUntil:'networkidle'});await page.evaluate(()=>{isTeacherAuthenticated=true;switchUnit('classroom');switchClassroomSubTab('assignments');});await page.locator('[onclick="exportClassroomCSV()"]').click();await page.locator('[onclick^="openStudentDetailModal"]').first().click();results.push({name:'broken buttons actual click errors',value:errors.slice()});
await probe('connection badge while offline',()=>({firebaseReady:window.isFirebaseReady,text:document.getElementById('view-classroom').innerText.includes('교실 실시간 네트워크 연결됨')}));
fs.writeFileSync(path.join(__dirname,'final-results.json'),JSON.stringify({results,errors,consoleErrors},null,2));console.log(JSON.stringify({results,errors,consoleErrors},null,2));await browser.close();server.close();})().catch(e=>{console.error(e);process.exit(1);});