const fs=require('fs'),path=require('path'),http=require('http');
const {chromium}=require('C:/Users/안동현/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..');
(async()=>{
const server=http.createServer((req,res)=>{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(pathname==='/js/data/config.js'||pathname==='/js/data/firebase-config.js'){res.setHeader('Content-Type','application/javascript');return res.end('window.firebaseDb=null;window.isFirebaseReady=false;');}if(pathname==='/api/chat'){res.writeHead(503);return res.end('Audit: AI network disabled');}const f=path.resolve(root,'.'+(pathname==='/'?'/index.html':pathname));if(!f.startsWith(root+path.sep)){res.writeHead(403);return res.end();}fs.readFile(f,(e,b)=>{if(e){res.writeHead(404);return res.end();}res.setHeader('Content-Type',f.endsWith('.js')?'application/javascript':f.endsWith('.css')?'text/css':'text/html');res.end(b);});});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});
const context=await browser.newContext({viewport:{width:1440,height:900}});
await context.route('**/*',route=>{const u=route.request().url();if(u.includes('firebase')||u.includes('upstage')||u.includes('firestore'))return route.abort();return route.continue();});
const page=await context.newPage();const errors=[],consoleErrors=[],results=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text());});page.on('dialog',d=>d.dismiss());
await page.goto(url,{waitUntil:'networkidle'});

async function probe(name,fn){try{results.push({name,value:await page.evaluate(fn)});}catch(e){results.push({name,error:e.message});}}
await page.evaluate(()=>{switchUnit('unit3','lab');switchFlowchartStep(4);});
for(const choice of ['yes','no']){await page.locator('#btn-l2-sim-run').click();await page.locator('#l2-btn-opt-'+choice).waitFor({state:'visible',timeout:12000});await page.locator('#l2-btn-opt-'+choice).click();await page.waitForFunction(()=>!isL2Simulating,{timeout:12000});results.push({name:'Step4 actual '+choice+' branch',value:await page.locator('.l2-sim-complete-toast').count()});}
await page.locator('#btn-l2-sim-run').click();await page.waitForTimeout(150);await page.locator('#btn-l2-sim-run').click();results.push({name:'Step4 stop',value:await page.evaluate(()=>({running:isL2Simulating,overlay:!!document.getElementById('l2-sim-choice-overlay')}))});
await page.goto(url,{waitUntil:'networkidle'});await page.evaluate(()=>{switchUnit('unit3','lab');switchFlowchartStep(5);});
await probe('numeric loop sums one through three',()=>{freeBlocks=[['s','terminal','시작'],['a','process','i = 1'],['b','process','sum = 0'],['d','decision','i <= 3'],['c','process','sum = sum + i'],['f','process','i = i + 1'],['o','io','sum 출력'],['e','terminal','종료']].map(([id,shape,text],n)=>({id,shape,text,x:100,y:n*90}));freeConnections=[['s','a'],['a','b'],['b','d'],['d','c','yes'],['c','f'],['f','d'],['d','o','no'],['o','e']].map(([from,to,fromPort='out'])=>({from,to,fromPort,toPort:'in'}));renderFreeCanvas();resetDebugger();for(let n=0;n<30&&!debuggerExec?.done;n++)stepDebugger();return {done:debuggerExec.done,steps:debuggerExec.steps,vars:debuggerExec.vars};});
await probe('constant comparison automatically evaluated',()=>{freeBlocks=[{id:'d',shape:'decision',text:'2 > 1',x:100,y:100},{id:'e',shape:'terminal',text:'종료',x:100,y:250}];freeConnections=[{from:'d',to:'e',fromPort:'yes'}];renderFreeCanvas();debuggerExec={curId:'d',prevId:null,vars:{},prevVars:{},steps:0,done:false,isWaitingUserChoice:false};stepDebugger();return {waiting:debuggerExec.isWaitingUserChoice,curId:debuggerExec.curId};});
await probe('orthogonal paths near alignment',()=>[0,1,4,7,8].map(dx=>({dx,path:generateManhattanPath(100,100,'out',100+dx,200,'in')})));
await page.goto(url,{waitUntil:'networkidle'});await page.evaluate(()=>{switchUnit('unit3','lab');switchFlowchartStep(5);freeConnections=[];renderFreeConnections();});await page.waitForTimeout(300);
var from=await page.locator('#port-out-blk-start').boundingBox(),to=await page.locator('#port-in-blk-p1').boundingBox();if(from&&to){await page.mouse.move(from.x+from.width/2,from.y+from.height/2);await page.mouse.down();await page.mouse.move(to.x+to.width/2,to.y+to.height/2,{steps:8});await page.mouse.up();results.push({name:'actual port drag creates connection',value:await page.evaluate(()=>freeConnections)});}
await probe('pan retains endpoint relative position',()=>{const before=document.querySelector('#free-flowchart-svg path[id]')?.getAttribute('d');canvasPanX=50;canvasPanY=30;applyCanvasPan();renderFreeConnections();return {before,after:document.querySelector('#free-flowchart-svg path[id]')?.getAttribute('d')};});
await probe('teacher CSV quote handling',async()=>{let captured;const orig=URL.createObjectURL,origClick=HTMLAnchorElement.prototype.click;URL.createObjectURL=b=>{captured=b;return 'blob:audit';};HTMLAnchorElement.prototype.click=function(){};evalService.exportNeisCSV('audit',[{num:1,name:'테스트"이름',status:'submitted',scores:{total:60}}]);URL.createObjectURL=orig;HTMLAnchorElement.prototype.click=origClick;return await captured.text();});
await probe('teacher score bounds',async()=>{await evalService.joinWaitingRoom('audit-bounds',1,'테스트');await evalService.overrideStudentScore('audit-bounds',1,150);return JSON.parse(sessionStorage.getItem('EVAL_STUDENTS_audit-bounds'))[0].scores;});
await probe('exam wall clock gap',()=>{studentEvalApp.sessionStatus='waiting';studentEvalApp.startExam({startTime:new Date().toISOString(),durationMinutes:30});const initial=studentEvalApp.remainingSeconds;const oldNow=Date.now;Date.now=()=>oldNow()+120000;studentEvalApp.renderTimer();Date.now=oldNow;clearInterval(studentEvalApp.timerInterval);return {initial,afterTwoMinuteClockGap:studentEvalApp.remainingSeconds};});
await probe('same theme click erases work',()=>{studentEvalApp.initPart3Canvas();studentEvalApp.addPart3Block('io');const before=studentEvalApp.answers.part3.blocks.length;studentEvalApp.selectPart3Theme(studentEvalApp.answers.part3.selectedThemeId);return {before,after:studentEvalApp.answers.part3.blocks.length};});
await page.goto('file:///'+root.replace(/\\/g,'/')+'/index.html',{waitUntil:'networkidle'});results.push({name:'direct file opening',value:await page.evaluate(()=>({protocol:location.protocol,appReady:typeof studentEvalApp==='object',missionCount:missions.length,roadmapVisible:!document.getElementById('view-roadmap').classList.contains('hidden')}))});
fs.writeFileSync(path.join(__dirname,'interaction-results.json'),JSON.stringify({results,errors,consoleErrors},null,2));console.log(JSON.stringify({results,errors,consoleErrors},null,2));await browser.close();server.close();})().catch(e=>{console.error(e);process.exitCode=1;});