const fs=require('fs'),path=require('path'),http=require('http');
const {chromium}=require('C:/Users/안동현/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..');
(async()=>{
const server=http.createServer((req,res)=>{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(pathname==='/js/data/config.js'||pathname==='/js/data/firebase-config.js'){res.setHeader('Content-Type','application/javascript');return res.end('window.firebaseDb=null;window.isFirebaseReady=false;');}if(pathname==='/api/chat'){res.writeHead(503);return res.end('Audit: AI network disabled');}const f=path.resolve(root,'.'+(pathname==='/'?'/index.html':pathname));if(!f.startsWith(root+path.sep)){res.writeHead(403);return res.end();}fs.readFile(f,(e,b)=>{if(e){res.writeHead(404);return res.end();}res.setHeader('Content-Type',f.endsWith('.js')?'application/javascript':f.endsWith('.css')?'text/css':'text/html');res.end(b);});});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});
const context=await browser.newContext({viewport:{width:1440,height:900}});
await context.route('**/*',route=>{const u=route.request().url();if(u.includes('firebase')||u.includes('upstage')||u.includes('firestore'))return route.abort();return route.continue();});
const page=await context.newPage();const errors=[],consoleErrors=[],results=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text());});page.on('dialog',d=>d.dismiss());
await page.goto(url,{waitUntil:'networkidle'});
const ids=await page.evaluate(()=>{const counts={};document.querySelectorAll('[id]').forEach(e=>counts[e.id]=(counts[e.id]||0)+1);return Object.entries(counts).filter(([k,v])=>v>1);});
results.push({name:'duplicate DOM ids',value:ids});
for(const [name,action] of [ ['roadmap',()=>switchUnit('roadmap')],['abstraction-concept',()=>switchUnit('unit1','concept')],['abstraction-quiz',()=>switchUnit('unit1','quiz')],['abstraction-lab',()=>switchUnit('unit1','lab')],['algorithm-concept',()=>switchUnit('unit2','concept')],['algorithm-quiz',()=>switchUnit('unit2','quiz')],['algorithm-lab',()=>switchUnit('unit2','lab')],['flowchart-concept',()=>switchUnit('unit3','concept')],['flowchart-quiz',()=>switchUnit('unit3','quiz')],...[1,2,3,4,5].map(n=>['flowchart-'+n,'switchUnit("unit3","lab");switchFlowchartStep('+n+')']),['eval',()=>switchUnit('eval')],['classroom',()=>{isTeacherAuthenticated=true;switchUnit('classroom');}]]){try{await page.evaluate(action);await page.waitForTimeout(150);await page.screenshot({path:path.join(__dirname,name+'.png')});results.push({name,value:await page.evaluate(()=>({views:[...document.querySelectorAll('main')].filter(e=>e.getBoundingClientRect().height>0).map(e=>e.id),overflow:document.documentElement.scrollWidth>innerWidth}))});}catch(e){results.push({name,error:e.message});}}
await page.evaluate(()=>{switchUnit('unit3','lab');switchFlowchartStep(5);});
results.push({name:'engine probes',value:await page.evaluate(()=>{
const out={};out.io=['나이 입력','합계 입력','기온 입력','점수를 입력받는다','결과 출력','나이 출력','1 + 2 출력'].map(t=>({text:t,input:parseIoInputVarName(t),output:parseIoOutputExpr(t)}));out.parser=['x = 1 + 2 * 3','x = (1+2)*3','x = 1.2.3','x = 1 / 0'].map(t=>{try{const a=parseFlowchartAssign(t);return {text:t,value:evalFlowchartAST(a.ast,{})};}catch(e){return {text:t,error:e.message};}});
freeBlocks=[{id:'s',shape:'terminal',text:'시작',x:200,y:20},{id:'e',shape:'terminal',text:'종료',x:200,y:160}];freeConnections=[{from:'s',to:'e',fromPort:'bottom',toPort:'top'}];nlCards=[];renderFreeCanvas();resetDebugger();stepDebugger();stepDebugger();out.emptyRunPassed=window.isFlowchartSimValidated;out.emptyConsistency=analyzeAlgorithmConsistency();
const app=window.studentEvalApp;app.answers.part3.blocks=[{id:'s',shape:'terminal',text:'시작'},{id:'e',shape:'terminal',text:'종료'},{id:'i',shape:'io',text:'엉뚱한 값'},{id:'d',shape:'decision',text:'아무 조건'},{id:'p',shape:'process',text:'아무 동작'}];app.answers.part3.connections=[{from:'d',to:'p'},{from:'d',to:'i'},{from:'i',to:'d'},{from:'p',to:'i'}];app.verifyPart3Flowchart();out.disconnectedExamPassed=app.answers.part3.isVerified;out.disconnectedExamScore=app.calculateScores().scores.part3;
return out;})});
const page2=await context.newPage();page2.on('dialog',d=>d.dismiss());await page2.goto(url,{waitUntil:'networkidle'});await page.evaluate(()=>{window.observedStudents=[];window.evalService.listenStudents('audit-test',v=>window.observedStudents=v);});await page2.evaluate(()=>window.evalService.joinWaitingRoom('audit-test',1,'테스트'));await page.waitForTimeout(200);results.push({name:'fallback teacher sees joined student',value:await page.evaluate(()=>window.observedStudents)});
await page2.evaluate(()=>{document.getElementById('eval-st-name').value='테스트';window.evalService.getDb=()=>null;switchUnit('eval');return studentEvalApp.enterWaitingRoom();});await page.evaluate(()=>window.evalService.startSession('2-1'));await page2.waitForTimeout(100);results.push({name:'exam started',value:await page2.evaluate(()=>({status:studentEvalApp.sessionStatus,remaining:studentEvalApp.remainingSeconds}))});await page.evaluate(()=>window.evalService.endSession('2-1'));await page2.waitForTimeout(100);results.push({name:'exam after teacher ends',value:await page2.evaluate(()=>({status:studentEvalApp.sessionStatus,submitted:studentEvalApp.isSubmitted,timerRunning:!!studentEvalApp.timerInterval}))});
await page2.evaluate(()=>{studentEvalApp.answers.part1.q1=2;switchUnit('unit3','lab');switchFlowchartStep(5);addNlCard('seq');});await page2.reload({waitUntil:'networkidle'});results.push({name:'reload retains work',value:await page2.evaluate(()=>({answers:studentEvalApp.answers.part1,nlCards,freeBlocks,storageKeys:Object.keys(sessionStorage)}))});
fs.writeFileSync(path.join(__dirname,'results.json'),JSON.stringify({results,errors,consoleErrors},null,2));console.log(JSON.stringify({results,errors,consoleErrors},null,2));await browser.close();server.close();})().catch(e=>{console.error(e);process.exitCode=1;});