const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const p=require('../js/core/assessment-policy.js'),{graphInput,enforceStructureEvidence}=require('../server/assessment-graph.cjs');
const fixtures=require('./fixtures/part3-calibration.cjs');
function student(scores=[5,5,5,5,10,10],part=fixtures[0].part){const s={status:'submitted',num:1,numStr:'01',name:'검증 학생',attemptId:'test',questionVersion:4,assessmentRubricVersion:p.ASSESSMENT_V2,answers:{part3:part},scores:{part1:15,part2:20}};s.review={proposal:{rubricVersion:p.ASSESSMENT_V2,attemptId:s.attemptId,sourceKey:p.assessmentSourceKey(part),criteria:p.ASSESSMENT_RUBRIC_V2.map((r,i)=>({id:r.id,score:scores[i],evidence:'합성 검증 근거'}))}};return s;}
test('all permitted rubric combinations respect floor, ceiling, and monotonicity',()=>{
 let checked=0;function visit(scores=[]){if(scores.length<6){for(const n of p.ASSESSMENT_RUBRIC_V2[scores.length].allowed)visit([...scores,n]);return;}const rows=student(scores).review.proposal.criteria,t=p.assessmentTotals(rows,p.ASSESSMENT_V2);assert.equal(t.total,Math.max(6,scores.reduce((a,b)=>a+b,0)));assert.ok(t.total<=40);for(let i=0;i<6;i++){const next=p.ASSESSMENT_RUBRIC_V2[i].allowed.find(n=>n>scores[i]);if(next!==undefined){const changed=rows.map((r,j)=>j===i?{...r,score:next}:r);assert.ok(p.assessmentTotals(changed,p.ASSESSMENT_V2).total>=t.total);}}checked++;}visit();assert.equal(checked,9216);
});
test('conversion rounds upward to even values only in export and stays in 0..30',()=>{assert.equal(p.assessmentConvert(75),24);assert.equal(p.assessmentConvert(100),30);assert.equal(p.assessmentConvert(NaN),null);for(let n=0;n<=1000;n++){const x=n/10,r=p.assessmentConvert(x);assert.equal(r%2,0);assert.ok(r>=x*.3&&r-x*.3<2.000001);}});
test('empty, conditions-only, meaningful singleton, and absent plan are distinct',()=>{
 assert.equal(p.assessmentIsEmpty(fixtures.at(-1).part),true);assert.equal(p.assessmentTotals(p.assessmentEmptyCriteria(),p.ASSESSMENT_V2).total,6);
 assert.equal(p.assessmentIsEmpty({plan:{conditions:'조용히'}}),false);assert.equal(p.assessmentIsEmpty({blocks:[{shape:'process',text:'물을 준다'}]}),false);
 const normalized=p.assessmentNormalizeAI(student().review.proposal.criteria,{plan:{goal:'목표'}},p.ASSESSMENT_V2);assert.deepEqual(normalized.slice(0,4).map(r=>r.score),[0,5,0,2]);
});
test('reject duplicate IDs, unsupported version, and nonpermitted scores',()=>{const rows=student().review.proposal.criteria;assert.throws(()=>p.validateAssessmentCriteria([...rows.slice(1),rows[1]],p.ASSESSMENT_V2));assert.throws(()=>p.validateAssessmentCriteria(rows.map((r,i)=>i===0?{...r,score:2}:r),p.ASSESSMENT_V2));assert.throws(()=>p.validateAssessmentCriteria(rows,'invented'));});
test('teacher correction wins; changed answer, attempt and version never reuse score',()=>{const s=student();s.review.proposal.total=999;assert.equal(p.assessmentEffectiveReview(s).total,40);s.review.confirmed={...s.review.proposal,criteria:student([5,5,5,2,8,10]).review.proposal.criteria};assert.equal(p.assessmentEffectiveReview(s).total,35);assert.equal(p.assessmentEffectiveReview({...s,attemptId:'different'}),null);assert.equal(p.assessmentEffectiveReview({...s,answers:{part3:{}}}),null);assert.equal(p.assessmentEffectiveReview({...s,assessmentRubricVersion:'open-design-v1'}),null);});
test('discarded islands are absent from AI input; all disconnected blocks retain content credit',()=>{const injection=fixtures.find(f=>f.id==='injection-island').part;assert.ok(!JSON.stringify(graphInput(injection)).includes('기존 기준'));assert.equal(graphInput(injection).blocks.length,4);const all=fixtures.find(f=>f.id==='unconnected').part;assert.equal(graphInput(all).blocks.length,4);const rows=enforceStructureEvidence(student().review.proposal.criteria,all);assert.equal(rows[4].score,10);assert.equal(rows[5].score,4);});
test('six-row workbook uses floor, provisional status and even conversion; corrections and stale results handled',()=>{
 const ctx={console,TextEncoder,Uint8Array,ArrayBuffer,DataView};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(fs.readFileSync('js/core/assessment-policy.js','utf8'),ctx);vm.runInContext(fs.readFileSync('js/core/excel-export.js','utf8'),ctx);
 const s=student([0,0,0,2,0,0],{}),sheets=ctx.window.excelExportService.buildWorkbookXmls('2-1',[s],{}),summary=sheets[0].xml,individual=sheets[1].xml;
 assert.match(summary,/<c r="J5"[^>]*><v>41<\/v>/);assert.match(summary,/<c r="L5"[^>]*><v>14<\/v>/);assert.match(summary,/잠정/);assert.match(individual,/현재 상태/);assert.match(individual,/순서도 구조·표현/);assert.match(individual,/최저점 보정 \+4점/);assert.match(individual,/D24:F24/);assert.match(individual,/B25:D25/);assert.match(individual,/<mergeCells count="12">/);
 s.review.confirmed={...s.review.proposal,criteria:student([3,3,3,3,6,6]).review.proposal.criteria};const edited=ctx.window.excelExportService.buildWorkbookXmls('2-1',[s],{});assert.match(edited[0].xml,/교사 정정/);assert.match(edited[0].xml,/<c r="J5"[^>]*><v>59<\/v>/);
 s.answers.part3={plan:{current:'수정된 답안'}};s.scores.total=99;const stale=ctx.window.excelExportService.buildWorkbookXmls('2-1',[s],{});assert.match(stale[0].xml,/채점 대기/);assert.doesNotMatch(stale[0].xml,/<c r="J5"[^>]*><v>99/);assert.match(stale[1].xml,/대기점 \/ 40점/);assert.match(stale[1].xml,/환산 대기/);
});
module.exports={student};
