const test=require('node:test'),assert=require('node:assert/strict');
const p=require('../js/core/assessment-policy.js'),{digest}=require('../server/objective-regrade.cjs'),{verify,operate}=require('../tools/apply-part3-regrade.cjs'),{fields,decode}=require('../tools/firebase-admin.cjs'),{selectRounds}=require('../tools/part3-snapshot.cjs');
function fixture(archived=false){const base='projects/donghyun-algo/databases/(default)/documents/classrooms/2-1'+(archived?'/archives/old':''),session={status:'ended',questionVersion:4,attemptId:'round',startTime:'2026-09-23T00:00:00Z'},data={status:'submitted',attemptId:'round',answers:{part3:{}},scores:{part1:30,part2:30,teacherOverride:99},review:{confirmed:{old:true}}},criteria=p.assessmentEmptyCriteria(),patch={assessmentRubricVersion:p.ASSESSMENT_V2,review:{proposal:{criteria,attemptId:'round',sourceKey:p.assessmentSourceKey({}),rubricVersion:p.ASSESSMENT_V2}},scores:{part1:30,part2:30,part3:6,total:66}};
 const group={classId:'2-1',archiveId:archived?'old':null,attemptId:'round',auditId:'part3-v2-round',session:{name:base,updateTime:'1',data:archived?{session}:session},students:[{source:{name:base+'/students/01',updateTime:'2',data},patch}]};const body={schemaVersion:1,project:'donghyun-algo',revision:p.ASSESSMENT_V2,groups:[group]};return {...body,planHash:digest(body)};}
function memory(plan){const docs=new Map();for(const g of plan.groups){for(const d of [g.session,...g.students.map(r=>r.source)])docs.set(d.name,{name:d.name,updateTime:d.updateTime,fields:fields(d.data)});}let tick=10,commits=0;
 return {docs,get commits(){return commits;},api:{fields,root:'https://firestore.googleapis.com/v1/projects/donghyun-algo/databases/(default)/documents',request:async(url,opts={})=>{if(url.endsWith(':runQuery'))return [...docs.values()].filter(d=>decode({mapValue:{fields:d.fields}}).kind==='part3-review-correction').map(document=>({document}));if(url.endsWith(':beginTransaction'))return {transaction:'t'};if(url.endsWith(':rollback'))return {};if(url.endsWith(':batchGet'))return opts.body.documents.map(name=>docs.has(name)?{found:structuredClone(docs.get(name))}:{missing:name});if(url.endsWith(':commit')){for(const w of opts.body.writes){if(w.currentDocument?.exists===false&&docs.has(w.update.name))throw Error('409');if(w.currentDocument?.updateTime&&docs.get(w.update.name)?.updateTime!==w.currentDocument.updateTime)throw Error('409');}for(const w of opts.body.writes){const prev=docs.get(w.update.name)?.fields||{},next=w.updateMask?{...prev}:{};for(const k of w.updateMask?.fieldPaths||[])delete next[k];Object.assign(next,w.update.fields);docs.set(w.update.name,{name:w.update.name,fields:next,updateTime:String(++tick)});}commits++;return {commitTime:String(tick)};}const name=url.replace('https://firestore.googleapis.com/v1/','');if(!docs.has(name))throw Error('404');return structuredClone(docs.get(name));}}};}
test('apply snapshots originals, preserves answer/objective, replaces approved manual score and is idempotent',async()=>{const plan=fixture(),m=memory(plan),row=plan.groups[0].students[0];await operate(plan,m.api,plan.planHash);const now=decode({mapValue:{fields:m.docs.get(row.source.name).fields}});assert.deepEqual(now.answers,row.source.data.answers);assert.equal(now.scores.part1,30);assert.equal(now.scores.teacherOverride,undefined);assert.equal(now.scores.total,66);assert.equal(now.review.confirmed,undefined);await operate(plan,m.api,plan.planHash);assert.equal(m.commits,1);await operate(plan,m.api,plan.planHash,true);assert.deepEqual(decode({mapValue:{fields:m.docs.get(row.source.name).fields}}),row.source.data);await operate(plan,m.api,plan.planHash,true);assert.equal(m.commits,2);});
test('archive source is never changed; restoration disables additive result without erasing backup',async()=>{const plan=fixture(true),m=memory(plan),row=plan.groups[0].students[0],before=structuredClone(m.docs.get(row.source.name));await operate(plan,m.api,plan.planHash);assert.deepEqual(m.docs.get(row.source.name),before);await operate(plan,m.api,plan.planHash,true);assert.deepEqual(m.docs.get(row.source.name),before);assert.ok([...m.docs.keys()].some(k=>k.includes('restore-part3-v2-round')));});
test('answer drift and later teacher correction prevent overwriting or rollback',async()=>{const plan=fixture(),m=memory(plan),row=plan.groups[0].students[0];m.docs.get(row.source.name).updateTime='changed';await assert.rejects(operate(plan,m.api,plan.planHash),/ANSWER_CHANGED/);assert.equal(m.commits,0);m.docs.get(row.source.name).updateTime='2';await operate(plan,m.api,plan.planHash);m.docs.get(row.source.name).fields.review=fields({x:{teacher:'edited'}}).x;await assert.rejects(operate(plan,m.api,plan.planHash,true),/CHANGED_AFTER_REGRADE/);});
test('invalid plan hashes and changed objective score are rejected',()=>{const plan=fixture();assert.throws(()=>verify(plan,'bad'));plan.groups[0].students[0].patch.scores.part2=0;delete plan.planHash;plan.planHash=digest(plan);assert.throws(()=>verify(plan,plan.planHash),/INVALID_PATCH/);});
test('archive correction made after migration prevents automatic restoration',async()=>{const plan=fixture(true),m=memory(plan);await operate(plan,m.api,plan.planHash);m.docs.set('edit',{name:'edit',fields:fields({kind:'part3-review-correction',sourceArchiveId:'old'})});await assert.rejects(operate(plan,m.api,plan.planHash,true),/ARCHIVED_TEACHER_CORRECTION_REQUIRES_REVIEW/);assert.equal(m.commits,1);});
test('selection takes two distinct actually started ended real rounds per class',()=>{const r=(id,start,version=4,status='ended',archiveId=null)=>({archiveId,session:{data:archiveId?{session:{attemptId:id,startTime:start,questionVersion:version,status}}:{attemptId:id,startTime:start,questionVersion:version,status}}});const rows=[r('a','2026-09-20'),r('b','2026-09-21'),r('b','2026-09-21',4,'ended','copy'),r('mock','2026-09-24',3),r('waiting',null),r('active','2026-09-25',4,'in_progress'),r('c','2026-09-22')];assert.deepEqual(selectRounds(rows).map(r=>r.attemptId),['c','b']);});
