// Real Edge DOM/actions with synthetic local records; no live Firebase or AI calls.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/안동현/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..'),out=path.join(root,'scratch/part3-v2/ui');fs.mkdirSync(out,{recursive:true});
(async()=>{const server=http.createServer((req,res)=>{const pathname=new URL(req.url,'http://localhost').pathname;if(pathname==='/js/data/firebase-config.js'){res.setHeader('Content-Type','application/javascript');return res.end('window.firebaseDb=null;function initFirebaseApp(){return null;}');}if(pathname==='/api/evaluation'){res.setHeader('Content-Type','application/json');return res.end(JSON.stringify({serverTime:Date.now()}));}if(!/^\/(index\.html|(?:js|css)\/[\w/.-]+)$/.test(pathname)){res.writeHead(404);return res.end();}const file=path.resolve(root,'.'+pathname);if(!file.startsWith(root+path.sep)){res.writeHead(403);return res.end();}fs.readFile(file,(e,data)=>{if(e){res.writeHead(404);return res.end();}res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(data);});});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;const errors=[],consoleErrors=[];
try{browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXE||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});const page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true});page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text());});page.on('dialog',d=>d.accept());page.setDefaultTimeout(7000);
await page.route('**/api/assessment',r=>r.fulfill({status:503,contentType:'application/json',body:'{"error":"합성 시험에서는 AI를 호출하지 않습니다."}'}));
await page.goto(`http://127.0.0.1:${server.address().port}/index.html?demo=1`,{waitUntil:'networkidle'});await page.locator('#nav-btn-classroom').click();await page.locator('#teacher-login-google').click();
await page.evaluate(()=>{
 const part={plan:{current:'화분의 흙이 마름',goal:'마른 흙에 물 주기',conditions:'젖으면 물을 주지 않음'},blocks:[],connections:[]},s={num:1,numStr:'01',name:'합성 검증 학생',questionVersion:4,status:'submitted',attemptId:'ui-v2',assessmentRubricVersion:ASSESSMENT_V2,answers:{part3:part},scores:{part1:30,part2:30}};
 s.review={proposal:{criteria:ASSESSMENT_RUBRIC_V2.map(r=>({id:r.id,score:r.max,evidence:'<img src=x> 합성 검증 근거'})),sourceKey:assessmentSourceKey(part),attemptId:s.attemptId,rubricVersion:ASSESSMENT_V2}};
 sessionStorage.setItem('EVAL_SESSION_2-1',JSON.stringify({classId:'2-1',status:'ended',questionVersion:4,assessmentRubricVersion:ASSESSMENT_V2,attemptId:s.attemptId}));sessionStorage.setItem('EVAL_STUDENTS_2-1',JSON.stringify([s]));currentSelectedClass='2학년 1반';currentLiveStudents=[s];setCurrentLiveSession({classId:'2-1',status:'ended',questionVersion:4,assessmentRubricVersion:ASSESSMENT_V2,attemptId:s.attemptId});window.uiStudent=s;openLiveStudentModal(1);
});
const box=page.locator('#classroom-assessment-review');assert.equal(await box.locator('input[type=number]').count(),6);assert.equal(await box.locator('img').count(),0);assert.ok(await box.getByRole('button',{name:'Solar AI 초벌 채점 요청',exact:true}).isDisabled());
await page.locator('#review-score-current').fill('2');await page.locator('#review-confirm-read').check();await page.locator('#review-confirm-save').click();assert.match(await box.textContent(),/허용 점수/);
await page.locator('#review-score-current').fill('4');await page.locator('#review-score-logic').fill('8');await page.locator('#review-confirm-read').check();await page.locator('#review-confirm-save').click();await page.waitForFunction(()=>!!JSON.parse(sessionStorage.getItem('EVAL_STUDENTS_2-1'))[0].review.confirmed);assert.equal(await page.evaluate(()=>assessmentEffectiveReview(JSON.parse(sessionStorage.getItem('EVAL_STUDENTS_2-1'))[0]).total),37);
for(const width of [1440,1100,768,540,390,320,1440]){await page.setViewportSize({width,height:1000});await page.locator('#review-confirm-save').scrollIntoViewIfNeeded();assert.ok(await page.locator('#review-confirm-save').isVisible());const bounds=await page.locator('#review-confirm-save').boundingBox();assert.ok(bounds.x>=0&&bounds.x+bounds.width<=width+2);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false);if([1440,390].includes(width))await page.screenshot({path:path.join(out,'teacher-'+width+'.png')});}
await page.evaluate(()=>{const s=JSON.parse(sessionStorage.getItem('EVAL_STUDENTS_2-1'))[0];const bytes=excelExportService.generateXlsxBinary({classId:'2-1',studentList:[s],classGrades:{}});window.exportBytes=Array.from(bytes);});fs.writeFileSync(path.join(out,'synthetic-report.xlsx'),Buffer.from(await page.evaluate(()=>window.exportBytes)));
assert.deepEqual(errors,[]);assert.deepEqual(consoleErrors,[]);console.log(JSON.stringify({passed:true,criteria:6,teacherCorrected:37,widths:[1440,1100,768,540,390,320],errors,consoleErrors}));
}finally{await browser?.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
